name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run build
            timeout-minutes: 600
            run: |
               export HOST_UID=$(stat -c "%u" $GITHUB_WORKSPACE)
               export HOST_GID=$(stat -c "%g" $GITHUB_WORKSPACE)
               echo "GitHub Workspace: ${{ github.workspace }}"
               echo "Host UID: $HOST_UID"
               echo "Host GID: $HOST_GID"
               stat -c '%u %g' ${GITHUB_WORKSPACE}
               chown -R ${HOST_UID}:${HOST_GID} $GITHUB_WORKSPACE
               stat -c '%u %g' ${GITHUB_WORKSPACE}
               docker run --rm \
                 --privileged \
                 -u ${HOST_UID}:${HOST_GID} \
                 -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
                 -e GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 -v /var/run/docker.sock:/var/run/docker.sock \
                 cuaesd/aesd-autotest:24-assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 bash -c "id"
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
          - name: Run full test
            timeout-minutes: 15
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./full-test.sh
