name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run build
            timeout-minutes: 600
            run: |
               pwd
               id
               stat -c "%u %g" .
               docker run --rm \
                 --privileged \
                 -u ${HOST_UID}:${HOST_GID} \
                 -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
                 -e GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
                 -v /workspaces/assignment-6-diogomatos3/actions-runner/_work/assignment-6-diogomatos3/assignment-6-diogomatos3:/workspaces/assignment-6-diogomatos3/actions-runner/_work/assignment-6-diogomatos3/assignment-6-diogomatos3 \
                 -v /var/run/docker.sock:/var/run/docker.sock \
                 cuaesd/aesd-autotest:24-assignment6-yocto \
                 --workdir=/workspaces/assignment-6-diogomatos3/actions-runner/_work/assignment-6-diogomatos3/assignment-6-diogomatos3 \
                 bash -c "id"
            working-directory: ${{github.workspace}}
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
          - name: Run full test
            timeout-minutes: 15
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./full-test.sh
